// Notifications model
// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const NotificationSchema = Mongoose.Schema(
    {
      author: { type: String, required: true }, // author
      recipient: { type: String, required: true }, //receveur
      message: { type: String, required: true }, // message
      type: { type: String, required: true }, //type
      location: { type: String, default: null }, // optional location
    },
    { timestamps: true }
  );

  return mongoose.model("Notification", NotificationSchema, "Notification");
};
