// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema(
    {
      email: String,
      salt: String,
      token: String,
      hash: String,
      image: [String],
      lastActionTime: Number,
      memberId: { type: String, unique: true },
      avatar: String,
      city: String,
      university: { type: String, default: "secret" },
      studies: { type: String, default: "secret" },
      firstName: String,
      isPersonalAccount: Boolean,
      askFriendSecurity: String,
      isPersonalAccount: Boolean,
      lastName: String,
      friends: [String], //array of User._id
      friendRequests: [String], //array of User._id
      blockList: [String],
      activities: [String], //array of Activity._id
      activityInvitations: [String],
      nativeLanguage: String,
      isVerified: { type: Boolean, default: false },
      sexe: String,
      userName: String,
      verificationCode: String,
      verificationCodeTime: Number,
      spokenLanguage: [Number],
      hobbies: [Number],
      phone: String,
      birthday: Number,
      children: Number,
      tobacco: Number,
      age: Number,
      evaluations: [String],
      alcohol: Number,
      about: String,
      chats: [String],
      updatedAt: Date,
      likes: [String],
      role: {
        id: [String], //array role id
        name: [String], //array role name
      },
    },

    {
      timestamps: true,
    }
  );

  return mongoose.model("user", schema, "User");
};
